name: claims_ml
channels:
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - notebook
  - tqdm
  - joblib
  - requests
  - beautifulsoup4
  - pillow
  - pyyaml
  - psutil
  - tornado
  - traitlets
  - matplotlib-inline
  - packaging
  - typing-extensions
  - setuptools
  - wheel
  - pip:
      - nbformat
      - nbconvert
